### ISSUE TITLE
Update files to use `.R` rather `r`

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam-to-fda#3]
![image](https://user-images.githubusercontent.com/10111024/219986975-7d133ef2-98a5-4e7b-b07a-1fbc2acee80d.png)

**Comment by laxamanaj** [comment]
Per guidance, here, I believe we need to revert back to `.r` instead of `.R.` 

Steven Haesendonckx
1:18 AM May 30
Example that uppercase is not allowed
chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/[https://www.fda.gov/media/85816/download](https://www.google.com/url?q=https://www.fda.gov/media/85816/download&sa=D&source=docs&ust=1688104874651554&usg=AOvVaw1nmP_LgOuIfsOv-xBMSi_0)

**Comment by laxamanaj** [comment]
No longer applicable as guidance is to use lowercase '.r' instead.  See : https://github.com/RConsortium/submissions-pilot3-adam/issues/115
