### ISSUE TITLE
adrg: avoid proprietary package installation from github

### ISSUE THREAD

**Issue by fb-elong** [RConsortium/submissions-pilot3-adam-to-fda#37]
In Page 26, step 6 of the adrg, it asks reviewer to install package from github (either using `renv` or `install_github`). The approach is not applicable for real study submission. 

Submission package should be self contained that include all source code from proprietary packages. https://github.com/RConsortium/submissions-pilot3-adam-to-fda 

More details can be found in https://r4csr.org/submission-package.html

**Comment by laxamanaj** [comment]
Thanks for your guidance here @fb-elong .  This was discussed in an R Consortium R Submissions WG meeting where FDA were ok to forego the use of {pkglite} for Pilot 3 : https://rconsortium.github.io/submissions-wg/minutes/2023-04-07/ .

We wanted to discern the analysis repo from the utility/helper functions, hence the approach we decided to go at this time.

Though, we do acknowledge that for proprietary utility functions, it's not usual to have this freely available to the public, we just wanted to test this approach with the FDA to see if this was ok with them as well.  One thought could be to provide FDA reviewers access to the proprietary github package during review.  Otherwise, {pkglite} is good guidance to follow for current studies planning to submit using open source R today.

For Pilot 3 we will await further feedback from FDA's current review.

**Comment by laxamanaj** [comment]
Per meeting minutes here : https://rconsortium.github.io/submissions-wg/minutes/2024-02-02/ FDA agreed with .zip approach to submit proprietary package.
